name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_iOS:
    runs-on: macos-latest
    steps:
    - name: Checkout Repo
    - uses: actions/checkout@v2
    - name: Setup Xcode
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build
      run: xcodebuild -scheme PermissionsSwiftUI -destination 'generic/platform=iOS' build
  test_iOS:
     runs-on: macos-latest
     steps:
     - name: Checkout Repo
     - uses: actions/checkout@v2
     - name: Setup Xcode
     - uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: latest-stable
     - name: Test
       run: xcodebuild -scheme PermissionsSwiftUI -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.3' test
  Swiftformat:
    name: Check swiftformat
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Install Swiftformat
        run: brew install swiftformat

      - name: Format Swift code
        run: swiftformat --verbose . --swiftversion 5.2
  SwiftDoc:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - name: Swift Doc
        uses: SwiftDocOrg/swift-doc@1.0.0-beta.5
        with:
          inputs: "Sources/PermissionsSwiftUI"
          module-name: PermissionsSwiftUI
          output: "Documentation"
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "Documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

