name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_iOS:
    runs-on: macos-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build
      run: xcodebuild -scheme PermissionsSwiftUI -destination 'generic/platform=iOS' build
  test_iOS:
     runs-on: macos-latest
     steps:
     - name: Checkout Repo
       uses: actions/checkout@v2
     - name: Setup Xcode
       uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: latest-stable
     - name: Test large screen device
       run: xcodebuild -scheme PermissionsSwiftUI -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max'  -only-testing:PermissionsSwiftUITests test
     - name: Test small screen device
       run: xcodebuild -scheme PermissionsSwiftUI -destination 'platform=iOS Simulator,name=iPod touch (7th generation)' -only-testing:PermissionsSwiftUISmallScreenTests test
  Swiftformat:
    name: Check swiftformat
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Install Swiftformat
        run: brew install swiftformat

      - name: Format Swift code
        run: swiftformat --verbose . --swiftversion 5.2
  Documentation_coverage:
    name: Documentation coverage
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Ready shell script
        run: chmod +x .github/documentation_coverage.sh
      - name: Execute shell script
        run: .github/documentation_coverage.sh
